export let data = [
  {
    slug: "spotitech",
    title: "SPOTITECH",
    cover: "/static/images/projects/spotitech.jpg",
    description: "Spotitech Project",
    date: "June 2022",
    medias: [{ url: "/static/images/projects/spotitech.jpg" }],
    stack: ["Symfony", "ReactJS"],
    link: "https://github.com/remytep/spotitech",
  },
  {
    slug: "ocr",
    title: "OCR",
    cover: "/static/images/projects/ocr.jpg",
    description: "OCR Project",
    date: "October 2022",
    medias: [{ url: "/static/images/projects/ocr.jpg" }],
    stack: ["Javascript", "ReactJS", "Node", "Express", "Socket.io"],
    link: "https://github.com/remytep/online-chat-room",
  },
  {
    slug: "mtn-snaps",
    title: "MTN SNAPS",
    cover: "/static/images/projects/mtnsnaps.jpg",
    description: "MTN Snaps project",
    date: "September 2022",
    medias: [{ url: "/static/images/projects/mtnsnaps.jpg" }],
    stack: ["ReactJS"],
    link: "https://github.com/remytep/mtn-snaps",
  },
  {
    slug: "portfolio",
    title: "PORTFOLIO",
    cover: "/static/images/projects/portfolio.jpg",
    description: "Portfolio project",
    date: "November 2022",
    medias: [{ url: "/static/images/projects/portfolio.jpg" }],
    stack: ["ReactJS", "Next", "Tailwind"],
    link: "https://github.com/remytep/portfolio",
  },
  {
    slug: "sprite-generator",
    title: "SPRITE GENERATOR",
    cover: "/static/images/projects/sprite.jpg",
    description: "Sprite Generator project",
    date: "April 2022",
    medias: [{ url: "/static/images/projects/sprite.jpg" }],
    stack: ["Php"],
    link: "https://github.com/remytep/sprite-generator",
  },
  {
    slug: "battle",
    title: "Battle",
    cover: "/static/images/projects/battle.jpg",
    description: "Corsican Battle project",
    date: "July 2022",
    medias: [{ url: "/static/images/projects/battle.jpg" }],
    stack: ["Javascript"],
    link: "https://github.com/remytep/corsican-battle",
  },
  {
    slug: "cinema",
    title: "CINEMA THEATER",
    cover: "/static/images/projects/cinema.jpg",
    description: "Cinema Theater project",
    date: "May 2022",
    medias: [{ url: "/static/images/projects/cinema.jpg" }],
    stack: ["Javascript", "Php"],
    link: "https://github.com/remytep/cinema-theater",
  },
];
